In [1]:
import pandas as pd
import math as m 
import numpy as np

In [2]:
df = pd.read_csv('Heart Disease.csv')

In [3]:
df.head(4)


HeartDisease    BMI Smoking AlcoholDrinking Stroke  PhysicalHealth  \
0           No  16.60     Yes              No     No             3.0   
1           No  20.34      No              No    Yes             0.0   
2           No  26.58     Yes              No     No            20.0   
3           No  24.21      No              No     No             0.0   

   MentalHealth DiffWalking     Sex  AgeCategory   Race Diabetic  \
0          30.0          No  Female        55-59  White      Yes   
1           0.0          No  Female  80 or older  White       No   
2          30.0          No    Male        65-69  White      Yes   
3           0.0          No  Female        75-79  White       No   

  PhysicalActivity  GenHealth  SleepTime Asthma KidneyDisease SkinCancer  
0              Yes  Very good        5.0    Yes            No        Yes  
1              Yes  Very good        7.0     No            No         No  
2              Yes       Fair        8.0    Yes            No         No  
3               No       Good        6.0     No            No        Yes

In [4]:
df.shape


(319795, 18)

In [5]:
df1=df.copy
df2=df.copy

# Encoding

In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [7]:
import numpy as np
from pandas.core.dtypes.common import is_numeric_dtype
for column in df.columns:
  if is_numeric_dtype(df[column]):
    continue
  else:
    df[column]=le.fit_transform(df[column])

In [8]:
df.head()

HeartDisease    BMI  Smoking  AlcoholDrinking  Stroke  PhysicalHealth  \
0             0  16.60        1                0       0             3.0   
1             0  20.34        0                0       1             0.0   
2             0  26.58        1                0       0            20.0   
3             0  24.21        0                0       0             0.0   
4             0  23.71        0                0       0            28.0   

   MentalHealth  DiffWalking  Sex  AgeCategory  Race  Diabetic  \
0          30.0            0    0            7     5         2   
1           0.0            0    0           12     5         0   
2          30.0            0    1            9     5         2   
3           0.0            0    0           11     5         0   
4           0.0            1    0            4     5         0   

   PhysicalActivity  GenHealth  SleepTime  Asthma  KidneyDisease  SkinCancer  
0                 1          4        5.0       1              0           1  
1                 1          4        7.0       0              0           0  
2                 1          1        8.0       1              0           0  
3                 0          2        6.0       0              0           1  
4                 1          4        8.0       0              0           0

In [9]:
y=df['HeartDisease']
y.value_counts()

0    292422
1     27373
Name: HeartDisease, dtype: int64

In [10]:
x=df.copy()
x=df.drop('HeartDisease', axis=1)
x.head(3)

BMI  Smoking  AlcoholDrinking  Stroke  PhysicalHealth  MentalHealth  \
0  16.60        1                0       0             3.0          30.0   
1  20.34        0                0       1             0.0           0.0   
2  26.58        1                0       0            20.0          30.0   

   DiffWalking  Sex  AgeCategory  Race  Diabetic  PhysicalActivity  GenHealth  \
0            0    0            7     5         2                 1          4   
1            0    0           12     5         0                 1          4   
2            0    1            9     5         2                 1          1   

   SleepTime  Asthma  KidneyDisease  SkinCancer  
0        5.0       1              0           1  
1        7.0       0              0           0  
2        8.0       1              0           0

# Xgboost

In [11]:
import xgboost 
from xgboost import XGBClassifier

In [12]:
xgb = XGBClassifier()

# Adaboost

In [13]:
from sklearn.ensemble import AdaBoostClassifier

In [14]:
ada = AdaBoostClassifier()

# Undersampling

In [15]:
from imblearn.under_sampling import NearMiss

In [16]:
NearMiss_obj = NearMiss()
new_x , new_y = NearMiss_obj.fit_resample(x,y)

In [17]:
new_y.value_counts()

0    27373
1    27373
Name: HeartDisease, dtype: int64

# ACCURACY USING XGBOOST

In [18]:
from sklearn.model_selection import KFold, cross_val_score

In [19]:
kfold = KFold(n_splits=4) #each fold contain 25% data

In [20]:
result = cross_val_score(xgb, new_x , new_y,cv=kfold) 

In [21]:
result

array([0.86717323, 0.71914956, 0.81250913, 0.80754055])

In [22]:
result.max()

0.8671732300723314

 # ACCURACY USING ADABOOST

In [23]:
result1 = cross_val_score(xgb, new_x , new_y,cv=kfold) 

In [24]:
result1

array([0.86717323, 0.71914956, 0.81250913, 0.80754055])

In [25]:
result1.max()

0.8671732300723314

# Accuracy using Decision Tree classifier

In [26]:
from sklearn.tree import DecisionTreeClassifier

In [27]:
clf = DecisionTreeClassifier() 

In [28]:
result2 = cross_val_score(clf, new_x , new_y,cv=kfold) 

In [29]:
result2

array([0.252064  , 0.60860671, 0.7913196 , 0.7886161 ])

In [30]:
result2.max()

0.791319596668128

In [35]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=1000)

In [36]:
result3 = cross_val_score(lr, new_x , new_y, cv=kfold,) 

In [37]:
result3

array([0.91765909, 0.77803755, 0.76647669, 0.74959813])

In [38]:
result3.mean()

0.8029428668594467